# -*- coding: utf-8 -*-
from pathlib import Path
path = Path("src/app/Main.tsx")
text = path.read_text(encoding="utf-8")
old = "                <div style={{ display: 'flex', gap: 10, flexWrap: 'wrap', marginBottom: 10 }}>\n                  {list.map(u => {\n                    const letter = u?.[0]?.toUpperCase() || '?';\n                    const color = u === username ? '#60a5fa' : '#22c55e';\n                    return (\n                      <div key={u} style={{ padding: '6px 10px', borderRadius: 8, border: '1px solid #1f2937', background: '#0f172a', display: 'flex', alignItems: 'center', gap: 8 }}>\n                        <span style={{ width: 28, height: 28, borderRadius: 999, background: '#0b1222', border: `1px solid ${color}`, display: 'inline-flex', alignItems: 'center', justifyContent: 'center', color, fontWeight: 700 }}>{letter}</span>\n                        <span style={{ fontWeight: 600 }}>{u}</span>\n                        {u === username && <span style={{ fontSize: 12, color: '#9ca3af' }}>(you)</span>}\n                      </div>\n                    );\n                  })}\n                  {list.length === 0 && (\n                    <div style={{ color: '#9ca3af', fontSize: 12 }}>No participants yet.</div>\n                  )}\n                </div>"
new = "                <div style={{ display: 'flex', gap: 10, flexWrap: 'wrap', marginBottom: 10 }}>\n                  {participantCards.map(part => {\n                    const user = part.user;\n                    const profile = userProfileCache[user];\n                    const avatar = profile?.avatarUrl || '/favicon.ico';\n                    const display = profile?.displayName || user;\n                    const color = part.status === 'connected' ? '#22c55e' : '#f59e0b';\n                    return (\n                      <div key={user} style={{ padding: '6px 10px', borderRadius: 8, border: '1px solid #1f2937', background: '#0f172a', display: 'flex', alignItems: 'center', gap: 8, minWidth: 160, flex: '1 1 220px' }}>\n                        <img src={avatar} alt={display} style={{ width: 32, height: 32, borderRadius: '50%', border: `2px solid ${color}` }} />\n                        <div style={{ display: 'grid', gap: 2 }}>\n                          <div style={{ fontWeight: 600 }}>{display}{user === username ? ' (you)' : ''}</div>\n                          <div style={{ fontSize: 12, color }}>{part.status === 'connected' ? 'Connected' : 'Ringing'}</div>\n                        </div>\n                      </div>\n                    );\n                  })}\n                  {participantCards.length === 0 && (\n                    <div style={{ color: '#9ca3af', fontSize: 12 }}>No participants yet.</div>\n                  )}\n                </div>"
if old not in text:
    raise SystemExit('list block not found')
text = text.replace(old, new, 1)
path.write_text(text, encoding='utf-8')
