# -*- coding: utf-8 -*-
from pathlib import Path
path = Path("src/app/Main.tsx")
text = path.read_text(encoding="utf-8")
old = "                <div style={{ display: 'flex', gap: 8, flexWrap: 'wrap' }}>\n                  <button\n                    type=\"button\"\n                    onClick={toggleMute}\n                    className=\"btn-ghost\"\n                    style={{ padding: '8px 12px', borderRadius: 8, border: '1px solid #1f2937', background: isMuted ? '#111827' : '#0f172a', color: '#e5e7eb' }}\n                  >\n                    <FontAwesomeIcon icon={isMuted ? faMicrophoneSlash : faMicrophone} /> {isMuted ? 'Unmute' : 'Mute'}\n                  </button>\n                  <button\n                    type=\"button\"\n                    onClick={toggleDeafen}\n                    className=\"btn-ghost\"\n                    style={{ padding: '8px 12px', borderRadius: 8, border: '1px solid #1f2937', background: isDeafened ? '#111827' : '#0f172a', color: '#e5e7eb' }}\n                  >\n                    <FontAwesomeIcon icon={faVolumeXmark} /> {isDeafened ? 'Undeafen' : 'Deafen'}\n                  </button>\n                  {callState === 'calling' && (\n                    <button\n                      type=\"button\"\n                      onClick={() => {\n                        setSelectedHaven('__dms__');\n                        if (activeCallDM) setSelectedDM(activeCallDM);\n                        setTimeout(() => {\n                          const el = chatScrollRef.current;\n                          if (el) el.scrollTop = el.scrollHeight;\n                        }, 50);\n                      }}\n                      className=\"btn-ghost\"\n                      style={{ padding: '8px 12px', borderRadius: 8, border: '1px solid #1f2937', background: '#0f172a', color: '#e5e7eb' }}\n                    >\n                      <FontAwesomeIcon icon={faPhone} /> Open DM\n                    </button>\n                  )}\n                  <button\n                    type=\"button\"\n                    onClick={endCall}\n                    className=\"btn-ghost\"\n                    style={{ padding: '8px 12px', borderRadius: 8, border: '1px solid #7f1d1d', background: '#7f1d1d', color: '#fff', marginLeft: 'auto' }}\n                  >\n                    Hang up\n                  </button>\n                </div>"
new = "                <div style={{ display: 'flex', gap: 8, flexWrap: 'wrap' }}>\n                  <button\n                    type=\"button\"\n                    onClick={toggleMute}\n                    className=\"btn-ghost\"\n                    style={{ padding: '8px 12px', borderRadius: 8, border: '1px solid #1f2937', background: isMuted ? '#111827' : '#0f172a', color: '#e5e7eb' }}\n                  >\n                    <FontAwesomeIcon icon={isMuted ? faMicrophoneSlash : faMicrophone} /> {isMuted ? 'Unmute' : 'Mute'}\n                  </button>\n                  <button\n                    type=\"button\"\n                    onClick={toggleDeafen}\n                    className=\"btn-ghost\"\n                    style={{ padding: '8px 12px', borderRadius: 8, border: '1px solid #1f2937', background: isDeafened ? '#111827' : '#0f172a', color: '#e5e7eb' }}\n                  >\n                    <FontAwesomeIcon icon={faVolumeXmark} /> {isDeafened ? 'Undeafen' : 'Deafen'}\n                  </button>\n                  <button\n                    type=\"button\"\n                    onClick={() => {\n                      setSelectedHaven('__dms__');\n                      if (activeCallDM) setSelectedDM(activeCallDM);\n                      setShowMobileNav(false);\n                      setTimeout(() => {\n                        const el = chatScrollRef.current;\n                        if (el) el.scrollTop = el.scrollHeight;\n                      }, 50);\n                    }}\n                    className=\"btn-ghost\"\n                    style={{ padding: '8px 12px', borderRadius: 8, border: '1px solid #1f2937', background: '#0f172a', color: '#e5e7eb' }}\n                  >\n                    <FontAwesomeIcon icon={faPhone} /> Jump to DM\n                  </button>\n                  <button\n                    type=\"button\"\n                    onClick={endCall}\n                    className=\"btn-ghost\"\n                    style={{ padding: '8px 12px', borderRadius: 8, border: '1px solid #7f1d1d', background: '#7f1d1d', color: '#fff', marginLeft: 'auto' }}\n                  >\n                    Hang up\n                  </button>\n                </div>"
if old not in text:
    raise SystemExit('action block not found')
text = text.replace(old, new, 1)
path.write_text(text, encoding='utf-8')
