import crypto from "node:crypto";import * as cookie from "cookie";import { appendSetCookie } from "./oidcCookies";import { base64UrlDecode } from "./base64";import { decryptPayload,encryptPayload,type EncryptedPayloadV1 } from "@/lib/security/aead";import { getSessionKeyRing } from "@/lib/security/keyRings";
const isProduction=process.env.NODE_ENV==="production",TTL=7*24*60*60,issuer="chitterhaven",audience="chitterhaven-web";
export type SessionUser={id:string;username:string;displayName?:string|null;avatar?:string|null;email?:string|null;roles?:string[]|null};type SessionPayload={sessionId:string;user:SessionUser;createdAt:string;expiresAt:number;issuer?:string;audience?:string;environment?:string};
export const getSessionCookieName=()=>process.env.CS_SESSION_COOKIE_NAME||"ch_session";const options=(maxAge:number)=>({httpOnly:true,secure:isProduction,sameSite:"lax" as const,path:"/",maxAge});
const encrypt=(p:SessionPayload)=>Buffer.from(JSON.stringify({sessionId:p.sessionId,encrypted:encryptPayload(Buffer.from(JSON.stringify({...p,issuer,audience,environment:process.env.NODE_ENV||"development"})),getSessionKeyRing(),{service:"chitterhaven",purpose:"session-cookie",recordId:p.sessionId})})).toString("base64url");
const legacy=(token:string):SessionPayload|null=>{const secret=process.env.CHITTERHAVEN_SESSION_LEGACY_SECRET;if(!secret)return null;try{const[ivPart,dataPart,tagPart]=token.split(".");const d=crypto.createDecipheriv("aes-256-gcm",crypto.createHash("sha256").update(secret).digest(),base64UrlDecode(ivPart));d.setAuthTag(base64UrlDecode(tagPart));return JSON.parse(Buffer.concat([d.update(base64UrlDecode(dataPart)),d.final()]).toString());}catch{return null;}};
const decrypt=(token:string):SessionPayload|null=>{try{const outer=JSON.parse(Buffer.from(token,"base64url").toString()) as{sessionId:string;encrypted:EncryptedPayloadV1};const p=JSON.parse(decryptPayload(outer.encrypted,getSessionKeyRing(),{service:"chitterhaven",purpose:"session-cookie",recordId:outer.sessionId}).toString()) as SessionPayload;if(p.sessionId!==outer.sessionId||p.issuer!==issuer||p.audience!==audience||p.environment!==(process.env.NODE_ENV||"development")||Date.now()>p.expiresAt)return null;return p;}catch{const p=legacy(token);return p&&Date.now()<=p.expiresAt?p:null;}};
export const createSessionPayload=(user:SessionUser,ttlSeconds=TTL):SessionPayload=>{const now=Date.now();return{sessionId:crypto.randomBytes(18).toString("base64url"),user,createdAt:new Date(now).toISOString(),expiresAt:now+ttlSeconds*1000};};
export const setSessionCookie=(res:{getHeader:any;setHeader:any},session:SessionPayload)=>appendSetCookie(res,cookie.serialize(getSessionCookieName(),encrypt(session),options(TTL)));export const clearSessionCookie=(res:{getHeader:any;setHeader:any})=>appendSetCookie(res,cookie.serialize(getSessionCookieName(),"",options(0)));export const readSessionFromRequest=(req:{headers:{cookie?:string}})=>{const token=cookie.parse(req.headers.cookie||"")[getSessionCookieName()];return token?decrypt(token):null;};
