import crypto from "node:crypto";import fs from "node:fs";import path from "node:path";import { decryptPayload,encryptPayload,type EncryptedPayloadV1,type KeyRing } from "./aead";
type Options<T>={filePath:string;purpose:string;ring:KeyRing;validate(value:unknown):value is T;legacySecret?:string;defaultValue?:()=>T};
const binding=(o:{filePath:string;purpose:string})=>({service:"chitterhaven",purpose:o.purpose,recordId:path.basename(o.filePath)});
const parse=<T>(raw:string,o:Options<T>)=>{const value:unknown=JSON.parse(raw);if(!o.validate(value))throw new Error(`Invalid ${o.purpose} data structure.`);return value;};
const lock=(filePath:string,action:()=>void)=>{const lockPath=`${filePath}.lock`;let fd:number;try{fd=fs.openSync(lockPath,"wx",0o600);}catch{throw new Error(`Concurrent encrypted-store write rejected: ${path.basename(filePath)}`);}try{action();}finally{fs.closeSync(fd);fs.unlinkSync(lockPath);}};
export const writeEncryptedJson=<T>(value:T,o:Options<T>)=>lock(o.filePath,()=>{if(!o.validate(value))throw new Error(`Refusing to write invalid ${o.purpose} data.`);const payload=encryptPayload(Buffer.from(JSON.stringify(value)),o.ring,binding(o));const serialized=JSON.stringify(payload);const temp=`${o.filePath}.${process.pid}.${crypto.randomUUID()}.tmp`;fs.writeFileSync(temp,serialized,{mode:0o600});const verified=decryptPayload(JSON.parse(fs.readFileSync(temp,"utf8")) as EncryptedPayloadV1,o.ring,binding(o));parse<T>(verified.toString("utf8"),o);fs.renameSync(temp,o.filePath);try{fs.chmodSync(o.filePath,0o600);}catch{}});
export const readEncryptedJson=<T>(o:Options<T>):T=>{if(!fs.existsSync(o.filePath)){if(o.defaultValue)return o.defaultValue();throw new Error(`${o.purpose} store does not exist.`);}const raw=fs.readFileSync(o.filePath);if(!raw.length)throw new Error(`${o.purpose} store is empty or corrupt.`);try{const envelope=JSON.parse(raw.toString("utf8")) as EncryptedPayloadV1;if(envelope?.version===1)return parse<T>(decryptPayload(envelope,o.ring,binding(o)).toString("utf8"),o);}catch(error){if(raw[0]===0x7b)throw error;}
  if(!o.legacySecret)throw new Error(`Legacy ${o.purpose} key is not configured.`);if(raw.length<=16)throw new Error(`Legacy ${o.purpose} ciphertext is corrupt.`);let value:T;try{const key=crypto.createHash("sha256").update(o.legacySecret).digest();const decipher=crypto.createDecipheriv("aes-256-cbc",key,raw.subarray(0,16));value=parse<T>(Buffer.concat([decipher.update(raw.subarray(16)),decipher.final()]).toString("utf8"),o);}catch{throw new Error(`Legacy ${o.purpose} ciphertext could not be validated; no data was overwritten.`);}
  const backup=`${o.filePath}.legacy-cbc.bak`;if(!fs.existsSync(backup))fs.copyFileSync(o.filePath,backup,fs.constants.COPYFILE_EXCL);writeEncryptedJson(value,o);return value;};
